services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    volumes:
      - prefect_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    networks:
      - prefect_network

  prefect:
    image: prefecthq/prefect:3.3.3-python3.12-conda
    # restart: always
    volumes:
      - prefect:/root/.prefect
    command: ["prefect", "server", "start"]
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_UI_URL=http://localhost:4200
      - PREFECT_API_URL=http://localhost:4200/api
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect@postgres:5432/prefect
      - PREFECT_API_DATABASE_ECHO=False
      - PREFECT_API_DATABASE_MIGRATE_ON_START=True
    ports:
      - 4200:4200
    networks:
      - prefect_network

  backend-prefect:
    build:
      context: source
      dockerfile: Dockerfile
    volumes:
      - ./source:/app
    user: 1000:1000
    depends_on:
      - prefect 
    environment:
      - PREFECT_API_URL=http://prefect:4200/api 

    networks:
      - prefect_network
    # command: ["python3", "wait-for-prefect.py", "python3", "app.py"]    
    command: ["python3", "app.py"]

volumes:
  prefect_pgdata:
    # driver: local
  prefect:
    # driver: local

networks:
  prefect_network: